### PR TITLE
CI: Use the latest stable Julia

### PR DESCRIPTION
**Pull request by DilumAluthge**
Hat-tip @tlienart

### CODE REVIEW

**Comment by DilumAluthge** [comment]
Looks like the preview deploy key needs to be regenerated.

**Review by TheCedarPrince — APPROVED** [review]
LGTM but how do we regenerate keys @DilumAluthge ? If you tell me how, I can take care of it and merge it in.

**Comment by TheCedarPrince** [comment]
Oh wait, I think I just figured it out. Let me see if I can finish this right now.

**Comment by DilumAluthge** [comment]
We actually have two keypairs:

1. Keypair 1. The public key is added as a deploy key (with write access) on this repo. The private key (~~Base64-encoded~~) is added as a GitHub secret on this repo named FRANKLIN_PRIV.
2. Keypair 2. The public key is added as a deploy key (with write access) on the https://github.com/JuliaHealth/juliahealth.github.io-previews repo. The private key (~~Base64-encoded~~) is added as a GitHub secret on this repo named FRANKLIN_PRIV_PREVIEW

**Comment by DilumAluthge** [comment]
Actually, the private keys shouldn't be Base64-encoded. They should be in their original form, with each private key starting with a line that looks something like `--- BEGIN PRIVATE KEY` and ending with a line that looks something like `--- END PRIVATE KEY`.

**Comment by TheCedarPrince** [comment]
Ha HA! Take that GitHub Actions! We have freed this action from the fiery inferno of failed deployments 



@DilumAluthge ! I am going to go ahead and merge since all checks are working and actions succeed. Previews look fantastic as well. Thanks for the guidance and help on this!

**Comment by TheCedarPrince** [comment]
Closes #114

**Comment by DilumAluthge** [comment]
@TheCedarPrince Can you update https://github.com/JuliaHealth/juliahealth.github.io/blob/dev/Project.toml to not pin to an old Franklin version?

**Pull request merged**
